definitions:
  steps:
    - step: &build-dev-docker-image
        name: 'Build Development Docker Image'
        script:
          - IMAGE_NAME=${BITBUCKET_REPO_SLUG}
          - echo "IMAGE_NAME is set to:\ ${IMAGE_NAME}"
          - docker build --tag "${IMAGE_NAME}:dev" .
          - docker save "${IMAGE_NAME}:dev" --output "${IMAGE_NAME}.tar"
        services:
          - docker
        caches:
          - docker
        artifacts:
          - "*.tar"
    - step: &build-prod-docker-image
        name: 'Building Production Docker Image'
        script:
          - IMAGE_NAME=${BITBUCKET_REPO_SLUG}
          - echo "IMAGE_NAME is set to:\ ${IMAGE_NAME}"
          - docker build --tag "${IMAGE_NAME}:${PROD_VERSION}" .
          - docker save "${IMAGE_NAME}:${PROD_VERSION}" --output "${IMAGE_NAME}.tar"
        services:
          - docker
        caches:
          - docker
        artifacts:
          - "*.tar"
pipelines:
  default:
    - parallel:
        - step:
            image: hadolint/hadolint:v2.12.0-alpine
            name: 'Docker Lint'
            script:
              - echo "Linting Dockerfile(s)"
              - hadolint Dockerfile || echo "found linting issues in Dockerfile"
        - step: *build-dev-docker-image
        - step:
            image: golang:1.21.1-alpine3.18
            name: 'Build & Test'
            script:
              - go build -o bin/sbom-utils
              - apk add bash
              - go test -v -covermode=count -coverprofile=profile.out sbom-utilities/utils
            artifacts:
              - "bin/*"
              - "profile.out"
        - step:
            image: golang:1.21.1-alpine3.18
            name: 'Check Go Formatting'
            script:
              - gofmt -s -d $(find . -name "*.go")
        - step:
            image: golang:1.21.1-alpine3.18
            name: 'Go Linter'
            script:
              - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.54.2
              - bin/golangci-lint run ./...
  branches:
    main:
      - step: *build-prod-docker-image
      - step:
          name: 'Publish Docker Image'
          deployment: Production
          trigger: manual
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker load --input "${IMAGE_NAME}.tar"
            - IMAGE=${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}
            - docker push "${IMAGE}:${VERSION}"
          services:
            - docker
